"""Run the H4 testbenches: `make sim` (all) or `python sim/run.py b01 b05` (some).

Writes build/sim/report.md (full, git-ignored) and refreshes the results block in
sim/README.md (committed). Exit code 1 if any check FAILs or a bench errors, so a regression
is visible. Since H5 the "proposal" scope IS the schematic (build/main); "current" checks keep the
pre-H5 (H3) schematic's failures as the before/after record.
"""

from __future__ import annotations

import importlib
import sys
import time
import traceback
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import spice  # noqa: E402
from benchlib import BUILD, Bench, Ctx  # noqa: E402

BENCHES = ["b01_power_path", "b02_buck_3v3", "b03_ldo_3v0", "b04_handset_port",
           "b05_mic_bias_led", "b06_speaker_amp", "b07_mic_frontend", "b08_nfc_coil",
           "b09_led_rail", "b10_battery_life", "b11_hook_field"]


def main(argv: list[str]) -> int:
    quick = "--quick" in argv
    wanted = [a for a in argv if not a.startswith("--")]
    todo = [m for m in BENCHES if not wanted or any(m.startswith(w) for w in wanted)]
    import os
    ctx = Ctx(quick=quick, vendor="--vendor" in argv or os.environ.get("VENDOR") == "1")
    BUILD.mkdir(parents=True, exist_ok=True)
    try:
        eng = spice.version()
    except spice.SimError as e:
        print(e, file=sys.stderr)
        return 2
    results: list[Bench] = []
    for name in todo:
        mod = importlib.import_module(f"benches.{name}")
        t0 = time.time()
        print(f"[{name}] ...", flush=True)
        try:
            b = mod.run(ctx)
        except Exception as exc:  # a broken bench is reported, the others still run
            b = Bench(name[:3], getattr(mod, "TITLE", name), getattr(mod, "REQS", ""), [], [])
            b.error = f"{type(exc).__name__}: {exc}"
            traceback.print_exc()
        b.seconds = time.time() - t0
        results.append(b)
        print(f"[{name}] H5 schematic {b.verdict}, pre-H5 {b.verdict_current} "
              f"({b.seconds:.0f} s)", flush=True)
        for c in b.checks:
            print(f"   {c.verdict:4} [{c.scope}] {c.name}: {c.value} (limit {c.limit})")
    report = render_report(results, eng)
    (BUILD / "report.md").write_text(report)
    if not wanted:
        update_readme(results, eng)
    print(f"report: {BUILD / 'report.md'}")
    return 0 if all(b.verdict == "PASS" for b in results) else 1  # judged on the proposal


def _cell(s: str) -> str:
    return str(s).replace("|", "\\|").replace("\n", " ")


def render_report(results: list[Bench], eng: str) -> str:
    out = ["# H4 simulation report", "",
           f"Generated by `make sim` on {time.strftime('%Y-%m-%d %H:%M')} with {eng}.", "",
           "Verdicts: **H5** = the schematic as built in H5 (the H4 proposal plus the owner "
           "decisions of 2026-09-30); **pre-H5** = the H3 schematic, kept as the before/after "
           "record (`n/a` where the circuit no longer exists). Check scope: `both`, `current` "
           "(pre-H5 only), `proposal` (H5), `alt` (an alternative rejected on this data).",
           "",
           "| Bench | H5 | pre-H5 | Checks (pass/fail/info) | Requirements |",
           "|---|---|---|---|---|"]
    for b in results:
        n = [sum(c.ok is v for c in b.checks) for v in (True, False, None)]
        out.append(f"| {b.key} {b.title} | **{b.verdict}** | {b.verdict_current} | "
                   f"{n[0]}/{n[1]}/{n[2]} | {b.reqs} |")
    for b in results:
        out += ["", f"## {b.key}: {b.title}", "", f"Requirements: {b.reqs}. Verdict: **{b.verdict}** "
                f"({getattr(b, 'seconds', 0):.0f} s).", ""]
        if b.error:
            out += [f"**Bench error:** `{b.error}`", ""]
        out += ["**Model provenance**", ""] + [f"- {p}" for p in b.provenance]
        out += ["", "**Assumptions**", ""] + [f"- {a}" for a in b.assumptions]
        out += ["", "| Check | Scope | Value | Limit | Verdict | Req. | Note |",
                "|---|---|---|---|---|---|---|"]
        for c in b.checks:
            out.append(f"| {_cell(c.name)} | {c.scope} | {_cell(c.value)} | {_cell(c.limit)} | "
                       f"{c.verdict} | {_cell(c.reqs)} | {_cell(c.note)} |")
        if b.notes:
            out += ["", "**Notes**", ""] + [f"- {x}" for x in b.notes]
    return "\n".join(out) + "\n"


def update_readme(results: list[Bench], eng: str) -> None:
    readme = HERE / "README.md"
    text = readme.read_text()
    start, end = "<!-- RESULTS -->", "<!-- /RESULTS -->"
    if start not in text or end not in text:
        return
    rows = [f"Last full run: {time.strftime('%Y-%m-%d')}, {eng.split(' (')[0]}.", "",
            "| Bench | H5 | pre-H5 | Key results |", "|---|---|---|---|"]
    for b in results:
        key = "; ".join(f"{c.name}: {c.value}" for c in b.checks if c.ok is not None and
                        getattr(c, "key", False)) or b.error
        if not key:
            judged = [c for c in b.checks if c.ok is not None and c.scope in ("both", "proposal")]
            key = "; ".join(f"{c.name}: {c.value}" for c in judged[:2])
        rows.append(f"| {b.key} {b.title} | **{b.verdict}** | {b.verdict_current} | "
                    f"{_cell(key)} |")
    head, rest = text.split(start, 1)
    _, tail = rest.split(end, 1)
    readme.write_text(head + start + "\n" + "\n".join(rows) + "\n" + end + tail)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
