"""Run the simulation benches: `make sim` (all) or `python sim/run.py b01` (some).

Writes build/sim/report.md (git-ignored) and refreshes the results block in sim/README.md.
Exit code 1 if any check FAILs or a bench errors.
"""

from __future__ import annotations

import importlib
import sys
import time
import traceback
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import spice  # noqa: E402
from benchlib import BUILD, Bench, Ctx  # noqa: E402

BENCHES = ["b01_ldo_load_step"]


def main(argv: list[str]) -> int:
    wanted = [a for a in argv if not a.startswith("--")]
    todo = [m for m in BENCHES if not wanted or any(m.startswith(w) for w in wanted)]
    BUILD.mkdir(parents=True, exist_ok=True)
    try:
        eng = spice.version()
    except spice.SimError as e:
        print(e, file=sys.stderr)
        return 2
    results: list[Bench] = []
    for name in todo:
        mod = importlib.import_module(f"benches.{name}")
        t0 = time.time()
        try:
            b = mod.run(Ctx())
        except Exception as exc:  # a broken bench is reported, the others still run
            b = Bench(name[:3], getattr(mod, "TITLE", name), [], [])
            b.error = f"{type(exc).__name__}: {exc}"
            traceback.print_exc()
        b.seconds = time.time() - t0
        results.append(b)
        print(f"[{name}] {b.verdict} ({b.seconds:.0f} s)", flush=True)
        for c in b.checks:
            print(f"   {c.verdict:4} {c.name}: {c.value} (limit {c.limit})")
    (BUILD / "report.md").write_text(render_report(results, eng))
    if not wanted:
        update_readme(results, eng)
    print(f"report: {BUILD / 'report.md'}")
    return 0 if all(b.verdict == "PASS" for b in results) else 1


def _cell(s) -> str:
    return str(s).replace("|", "\\|").replace("\n", " ")


def render_report(results: list[Bench], eng: str) -> str:
    out = ["# Simulation report", "",
           f"Generated by `make sim` on {time.strftime('%Y-%m-%d %H:%M')} with {eng}.", ""]
    for b in results:
        out += [f"## {b.key}: {b.title}", "", f"Verdict: **{b.verdict}**.", ""]
        if b.error:
            out += [f"**Bench error:** `{b.error}`", ""]
        out += ["**Model provenance**", ""] + [f"- {p}" for p in b.provenance]
        out += ["", "**Assumptions**", ""] + [f"- {a}" for a in b.assumptions]
        out += ["", "| Check | Value | Limit | Verdict | Note |", "|---|---|---|---|---|"]
        out += [f"| {_cell(c.name)} | {_cell(c.value)} | {_cell(c.limit)} | {c.verdict} | "
                f"{_cell(c.note)} |" for c in b.checks]
        out.append("")
    return "\n".join(out) + "\n"


def update_readme(results: list[Bench], eng: str) -> None:
    readme = HERE / "README.md"
    text = readme.read_text()
    start, end = "<!-- RESULTS -->", "<!-- /RESULTS -->"
    if start not in text or end not in text:
        return
    rows = [f"Last full run: {time.strftime('%Y-%m-%d')}, {eng.split(' (')[0]}.", "",
            "| Check | Value | Limit | Verdict |", "|---|---|---|---|"]
    for b in results:
        rows += [f"| {b.key}: {_cell(c.name)} | {_cell(c.value)} | {_cell(c.limit)} | "
                 f"{c.verdict} |" for c in b.checks]
    head, rest = text.split(start, 1)
    _, tail = rest.split(end, 1)
    readme.write_text(head + start + "\n" + "\n".join(rows) + "\n" + end + tail)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
