// Generates docs/protocol.md from the zod schemas: `npm run docs:protocol`.
import { writeFileSync } from "node:fs";
import { z } from "zod";
import {
  AppToServer,
  DeviceToServer,
  MAX_MESSAGE_BYTES,
  PROTOCOL_VERSION,
  ServerToApp,
  ServerToDevice,
} from "../src/index.ts";

type JsonSchema = {
  description?: string;
  type?: string | string[];
  enum?: unknown[];
  const?: unknown;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  anyOf?: JsonSchema[];
  pattern?: string;
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
};

function typeOf(s: JsonSchema): string {
  if (s.const !== undefined) return `\`${JSON.stringify(s.const)}\``;
  if (s.enum) return s.enum.map((v) => `\`${JSON.stringify(v)}\``).join(" \\| ");
  if (s.anyOf) return s.anyOf.map(typeOf).join(" \\| ");
  if (s.type === "array" && s.items) return `${typeOf(s.items)}[]`;
  if (s.type === "object" && s.properties) {
    return `{ ${Object.entries(s.properties)
      .map(([k, v]) => `${k}${s.required?.includes(k) ? "" : "?"}: ${typeOf(v)}`)
      .join(", ")} }`;
  }
  const t = Array.isArray(s.type) ? s.type.join(" \\| ") : (s.type ?? "any");
  const bounds: string[] = [];
  if (s.minimum !== undefined && s.minimum > Number.MIN_SAFE_INTEGER) bounds.push(`≥${s.minimum}`);
  if (s.maximum !== undefined && s.maximum < Number.MAX_SAFE_INTEGER) bounds.push(`≤${s.maximum}`);
  if (s.minLength !== undefined && s.minLength === s.maxLength) bounds.push(`len ${s.minLength}`);
  else {
    if (s.minLength !== undefined && s.minLength > 1) bounds.push(`len ≥${s.minLength}`);
    if (s.maxLength !== undefined) bounds.push(`len ≤${s.maxLength}`);
  }
  if (s.pattern && !s.pattern.startsWith("^[A-Za-z0-9_-]")) bounds.push(`\`${s.pattern}\``);
  return bounds.length ? `${t} (${bounds.join(", ")})` : t;
}

function section(title: string, union: z.ZodType): string {
  const schema = z.toJSONSchema(union, { io: "input" }) as {
    oneOf?: JsonSchema[];
    anyOf?: JsonSchema[];
  };
  const variants = schema.oneOf ?? schema.anyOf ?? [];
  const out = [`## ${title}\n`];
  for (const v of variants) {
    const props = v.properties ?? {};
    out.push(`### \`${String(props.t?.const)}\`\n`);
    if (v.description) out.push(`${v.description}\n`);
    out.push("| Field | Type | Required | Notes |", "|---|---|---|---|");
    for (const [name, p] of Object.entries(props)) {
      if (name === "t") continue;
      const notes = (p.description ?? "").replace(/\|/g, "\\|");
      out.push(
        `| \`${name}\` | ${typeOf(p)} | ${v.required?.includes(name) ? "yes" : ""} | ${notes} |`,
      );
    }
    out.push("");
  }
  return out.join("\n");
}

const doc = `<!-- Generated by packages/protocol/scripts/gen-docs.ts. Do not edit by hand. -->
# OpenTinCan wire protocol v${PROTOCOL_VERSION}

Devices and companion apps hold one WebSocket to the backend. Every frame is a UTF-8 JSON object
of at most ${MAX_MESSAGE_BYTES} bytes with a string discriminator \`t\`. Any message may carry an
optional \`id\` (URL-safe, ≤64 chars); an \`error\` reply echoes it as \`ref\`. Unknown fields are
ignored; unknown \`t\` values are rejected with \`bad_message\`.

**Device connection:** \`hello\` → (unpaired) \`pair.begin\` → \`pair.code\` … \`pair.done\`, then reconnect;
(paired) \`auth.challenge\` → \`auth.proof\` → \`config\`. After that, call control and signaling.

**App connection:** \`app.hello\` (session token from HTTP login) → \`app.ready\`.

**Endpoints and routing hints.** Devices connect to \`/ws/device\`, adding \`?device=<deviceId>\`
once paired; apps connect to \`/ws/app?household=<householdId>\`. Hints only route the socket (to
the household's Durable Object on Cloudflare; the self-hosted server ignores them) — every
connection is still authenticated by the handshake. Keep-alive \`{"t":"ping"}\` must be sent
byte-for-byte as shown so hibernating servers can answer it without waking.

${section("Device → server", DeviceToServer)}
${section("Server → device", ServerToDevice)}
${section("App → server", AppToServer)}
${section("Server → app", ServerToApp)}`;

const target = new URL("../../../docs/protocol.md", import.meta.url);
writeFileSync(target, `${doc.trimEnd()}\n`);
console.log(`wrote ${target.pathname}`);
