// Generates docs/protocol.md from the zod schemas: `npm run docs:protocol`.
import { writeFileSync } from "node:fs";
import { z } from "zod";
import {
  AppToServer,
  DEVICE_FEATURES,
  DeviceToServer,
  MAX_MESSAGE_BYTES,
  MIN_PROTOCOL_VERSION,
  PROTOCOL_VERSION,
  ServerToApp,
  ServerToDevice,
} from "../src/index.ts";

type JsonSchema = {
  description?: string;
  type?: string | string[];
  enum?: unknown[];
  const?: unknown;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  anyOf?: JsonSchema[];
  pattern?: string;
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
};

function typeOf(s: JsonSchema): string {
  if (s.const !== undefined) return `\`${JSON.stringify(s.const)}\``;
  if (s.enum) return s.enum.map((v) => `\`${JSON.stringify(v)}\``).join(" \\| ");
  if (s.anyOf) return s.anyOf.map(typeOf).join(" \\| ");
  if (s.type === "array" && s.items) return `${typeOf(s.items)}[]`;
  if (s.type === "object" && s.properties) {
    return `{ ${Object.entries(s.properties)
      .map(([k, v]) => `${k}${s.required?.includes(k) ? "" : "?"}: ${typeOf(v)}`)
      .join(", ")} }`;
  }
  const t = Array.isArray(s.type) ? s.type.join(" \\| ") : (s.type ?? "any");
  const bounds: string[] = [];
  if (s.minimum !== undefined && s.minimum > Number.MIN_SAFE_INTEGER) bounds.push(`≥${s.minimum}`);
  if (s.maximum !== undefined && s.maximum < Number.MAX_SAFE_INTEGER) bounds.push(`≤${s.maximum}`);
  if (s.minLength !== undefined && s.minLength === s.maxLength) bounds.push(`len ${s.minLength}`);
  else {
    if (s.minLength !== undefined && s.minLength > 1) bounds.push(`len ≥${s.minLength}`);
    if (s.maxLength !== undefined) bounds.push(`len ≤${s.maxLength}`);
  }
  if (s.pattern && !s.pattern.startsWith("^[A-Za-z0-9_-]")) bounds.push(`\`${s.pattern}\``);
  return bounds.length ? `${t} (${bounds.join(", ")})` : t;
}

function section(title: string, union: z.ZodType): string {
  const schema = z.toJSONSchema(union, { io: "input" }) as {
    oneOf?: JsonSchema[];
    anyOf?: JsonSchema[];
  };
  const variants = schema.oneOf ?? schema.anyOf ?? [];
  const out = [`## ${title}\n`];
  for (const v of variants) {
    const props = v.properties ?? {};
    out.push(`### \`${String(props.t?.const)}\`\n`);
    if (v.description) out.push(`${v.description}\n`);
    out.push("| Field | Type | Required | Notes |", "|---|---|---|---|");
    for (const [name, p] of Object.entries(props)) {
      if (name === "t") continue;
      const notes = (p.description ?? "").replace(/\|/g, "\\|");
      out.push(
        `| \`${name}\` | ${typeOf(p)} | ${v.required?.includes(name) ? "yes" : ""} | ${notes} |`,
      );
    }
    out.push("");
  }
  return out.join("\n");
}

const doc = `<!-- Generated by packages/protocol/scripts/gen-docs.ts. Do not edit by hand. -->
# Open Lounge Phone wire protocol v${PROTOCOL_VERSION}

Devices and companion apps hold one WebSocket to the backend. Every frame is a UTF-8 JSON object
of at most ${MAX_MESSAGE_BYTES} bytes with a string discriminator \`t\`. Any message may carry an
optional \`id\` (URL-safe, ≤64 chars); an \`error\` reply echoes it as \`ref\`. Unknown fields are
ignored; a message of an unknown \`t\` is answered with \`error\` \`bad_message\` naming it in
\`unsupported\`, and the connection stays open.

**Device connection:** \`hello\` → (unpaired) \`pair.begin\` → \`pair.code\` … \`pair.done\`, then reconnect;
(paired) \`auth.challenge\` → \`auth.proof\` → \`config\`. After that, call control and signaling.

**App connection:** \`app.hello\` (session token from HTTP login) → \`app.ready\`.

**Endpoints and routing hints.** Devices connect to \`/ws/device\`, adding \`?device=<deviceId>\`
once paired; apps connect to \`/ws/app?household=<householdId>\`. Hints only route the socket (to
the household's Durable Object on Cloudflare; the self-hosted server ignores them) — every
connection is still authenticated by the handshake. Keep-alive \`{"t":"ping"}\` must be sent
byte-for-byte as shown so hibernating servers can answer it without waking.

## Versions and compatibility

- **Protocol version.** \`PROTOCOL_VERSION\` (now ${PROTOCOL_VERSION}) changes only for breaking
  changes. Additive changes keep it: new optional fields, new message types, new values behind a
  server feature. Removing or renaming a field, making one required (or a required one optional),
  changing a field's type, meaning or limits, or a new value in a closed enum is breaking.
- **What a client says.** \`hello\` carries \`proto\` (the protocol version the phone speaks) and
  \`fw\` (its firmware version; semver on hardware, e.g. \`0.6.0\`); \`app.hello\` carries \`proto\`.
- **What the server says.** It accepts protocol version${MIN_PROTOCOL_VERSION === PROTOCOL_VERSION ? ` ${PROTOCOL_VERSION}` : `s ${MIN_PROTOCOL_VERSION}–${PROTOCOL_VERSION}`}
  (\`MIN_PROTOCOL_VERSION\`..\`PROTOCOL_VERSION\`): when \`PROTOCOL_VERSION\` is bumped, the previous
  version stays accepted for at least 12 months. \`config.server\` and \`app.ready.server\` tell the
  client the range, the software version and the optional features it offers
  (${DEVICE_FEATURES.map((f) => `\`${f}\``).join(", ")}), so a client can leave out what a server
  doesn't offer; clients ignore names they don't know.
- **Outside the range.** A client older than the server accepts gets, for a phone, a \`config\`
  with \`update\` (show \`message\`, e.g. \`UPDATE NEEDED\`, and don't treat the phone as signed in),
  then \`error\` \`unsupported_version\` with \`server\`, and the connection closes (4400). A client
  newer than the server gets the same \`error\` (the message says the server is older) and may
  reconnect speaking a version in \`server.protocol\` if it can.
- **Tolerance, both ways.** Receivers ignore unknown fields (the schemas strip them; size limits
  still apply) and never disconnect for an unknown message type. Clients drop unknown server
  messages and optional fields they can't read; firmware ignores both.
- **Frozen vectors.** \`tests/conformance/protocol-v1/\` holds example messages (\`hello\`, pairing,
  \`auth.proof\`, \`config\`, calls) and a snapshot of every v1 schema; their tests must keep passing
  for v1 (see CONTRIBUTING.md).

${section("Device → server", DeviceToServer)}
${section("Server → device", ServerToDevice)}
${section("App → server", AppToServer)}
${section("Server → app", ServerToApp)}`;

const target = new URL("../../../docs/protocol.md", import.meta.url);
writeFileSync(target, `${doc.trimEnd()}\n`);
console.log(`wrote ${target.pathname}`);
