// Generated by firmware/tools/gen_board.py from hardware/build/main/gpio_map.json.
// Do not edit by hand: change hardware/schematic/pin_table.yaml and regenerate.
// Board: Open Lounge Phone main board, rev A (M3); module: ESP32-S3-WROOM-1U-N16R8 (16 MB flash, 8 MB octal PSRAM)
#pragma once

#include "sdkconfig.h"

// Keys: active low with internal pull-ups, in protocol order (index = button index;
// 10 = MENU, 11 = BACK).
#define PIN_KEY_1_HW             3
#define PIN_KEY_2_HW             46
#define PIN_KEY_3_HW             9
#define PIN_KEY_4_HW             10
#define PIN_KEY_5_HW             11
#define PIN_KEY_6_HW             43  // UART0 pin: the simulator build moves it (CONFIG_OLP_SIM)
#define PIN_KEY_7_HW             44  // UART0 pin: the simulator build moves it (CONFIG_OLP_SIM)
#define PIN_KEY_8_HW             42
#define PIN_KEY_9_HW             41
#define PIN_KEY_0_HW             40
#define PIN_KEY_MENU_HW          12
#define PIN_KEY_BACK_HW          39

#define PIN_HOOK                 2  // low = handset on the hook (internal pull-up)
#define PIN_JACK_DET             4  // high = plug in (internal pull-up)
#define PIN_BUZZER               8  // piezo via NPN, ~4 kHz
#define PIN_STATUS_LED           1  // active high
#define PIN_BOOT                 0

#define PIN_EPD_CLK              13
#define PIN_EPD_DIN              14
#define PIN_EPD_CS               47
#define PIN_EPD_DC               21
#define PIN_EPD_RST              38
#define PIN_EPD_BUSY             48

#define PIN_I2C_SDA              18
#define PIN_I2C_SCL              17
#define CODEC_I2C_ADDR           0x18  // ES8311
#define PIN_I2S_MCLK             16
#define PIN_I2S_BCLK             6
#define PIN_I2S_WS               5
#define PIN_I2S_DOUT             15  // to the codec (playback)
#define PIN_I2S_DIN              7  // from the codec (record)

// The Wokwi ESP32-S3 prints its console on UART0 (IO43/IO44), where the board has keys 6
// and 7; the simulator build moves those two keys to free pins (no PSRAM in the sim).
#if CONFIG_OLP_SIM
#define PIN_KEY_6 35
#define PIN_KEY_7 36
#else
#define PIN_KEY_6 PIN_KEY_6_HW
#define PIN_KEY_7 PIN_KEY_7_HW
#endif
#define PIN_KEY_1 PIN_KEY_1_HW
#define PIN_KEY_2 PIN_KEY_2_HW
#define PIN_KEY_3 PIN_KEY_3_HW
#define PIN_KEY_4 PIN_KEY_4_HW
#define PIN_KEY_5 PIN_KEY_5_HW
#define PIN_KEY_8 PIN_KEY_8_HW
#define PIN_KEY_9 PIN_KEY_9_HW
#define PIN_KEY_0 PIN_KEY_0_HW
#define PIN_KEY_MENU PIN_KEY_MENU_HW
#define PIN_KEY_BACK PIN_KEY_BACK_HW

#define KEY_COUNT 12
#define KEY_MENU_INDEX 10
#define KEY_BACK_INDEX 11
#define KEY_PINS { PIN_KEY_1, PIN_KEY_2, PIN_KEY_3, PIN_KEY_4, PIN_KEY_5, PIN_KEY_6, PIN_KEY_7, PIN_KEY_8, PIN_KEY_9, PIN_KEY_0, PIN_KEY_MENU, PIN_KEY_BACK }
#define KEY_NAMES { "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "MENU", "BACK" }
