// Deploys one Open Lounge Phone instance to the Cloudflare account wrangler is logged in to.
//
//   node scripts/deploy.ts --instance l1 --domain l1.openloungephone.app [--no-ai]
//                          [--turn-key-id ID --turn-key-token TOKEN] [--new-setup-token]
//
// Idempotent: creates the D1 database and R2 bucket only if missing, applies pending
// migrations, deploys the Worker on the custom domain, and on first run sets a one-time
// SETUP_TOKEN secret and prints the setup link. Account-specific IDs are written to
// instances/<instance>.json and instances/<instance>.wrangler.jsonc, which are gitignored.
import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";

const APP = fileURLToPath(new URL("..", import.meta.url));
const INSTANCES = `${APP}instances`;

const { values: args } = parseArgs({
  options: {
    instance: { type: "string" },
    domain: { type: "string" },
    "no-ai": { type: "boolean", default: false },
    "turn-key-id": { type: "string" },
    "turn-key-token": { type: "string" },
    "new-setup-token": { type: "boolean", default: false },
  },
});

const instance = args.instance ?? "";
const domain = args.domain ?? "";
if (!/^[a-z0-9][a-z0-9-]{0,30}$/.test(instance) || !/^[a-z0-9.-]+\.[a-z]{2,}$/.test(domain)) {
  console.error("usage: node scripts/deploy.ts --instance <name> --domain <host.example.com>");
  process.exit(2);
}

interface InstanceState {
  instance: string;
  domain: string;
  worker: string;
  database: { name: string; id: string };
  bucket: string;
  ai: boolean;
  setupTokenSet: boolean;
}

const statePath = `${INSTANCES}/${instance}.json`;
const configPath = `${INSTANCES}/${instance}.wrangler.jsonc`;
mkdirSync(INSTANCES, { recursive: true });
const previous: Partial<InstanceState> = existsSync(statePath)
  ? JSON.parse(readFileSync(statePath, "utf8"))
  : {};

function wrangler(argv: string[], input?: string): string {
  const res = spawnSync("npx", ["wrangler", ...argv], {
    cwd: APP,
    encoding: "utf8",
    input,
    stdio: [input === undefined ? "inherit" : "pipe", "pipe", "pipe"],
  });
  if (res.status !== 0) {
    throw new Error(`wrangler ${argv.join(" ")} failed:\n${res.stdout}\n${res.stderr}`);
  }
  return res.stdout;
}

const step = (msg: string) => console.log(`\n▸ ${msg}`);

// --- D1 -----------------------------------------------------------------------------
const dbName = `openloungephone-${instance}`;
step(`D1 database ${dbName}`);
type D1Row = { uuid: string; name: string };
const findDb = () =>
  (JSON.parse(wrangler(["d1", "list", "--json"])) as D1Row[]).find((d) => d.name === dbName);
let db = findDb();
if (!db) {
  wrangler(["d1", "create", dbName]);
  db = findDb();
  if (!db) throw new Error(`created ${dbName} but can't find it`);
  console.log(`  created ${db.uuid}`);
} else {
  console.log(`  exists ${db.uuid}`);
}

// --- R2 -----------------------------------------------------------------------------
const bucket = `openloungephone-${instance}-voicemail`;
step(`R2 bucket ${bucket}`);
if (wrangler(["r2", "bucket", "list"]).includes(`name:           ${bucket}`)) {
  console.log("  exists");
} else {
  wrangler(["r2", "bucket", "create", bucket]);
  console.log("  created");
}

// --- instance wrangler config ---------------------------------------------------------
const ai = !args["no-ai"];
step(`config ${configPath}`);
const base = JSON.parse(
  readFileSync(`${APP}wrangler.jsonc`, "utf8")
    .split("\n")
    .filter((l) => !l.trim().startsWith("//"))
    .join("\n"),
) as Record<string, unknown> & { assets: Record<string, unknown> };
const worker = `openloungephone-${instance}`;
const config = {
  ...base,
  $schema: "../../../node_modules/wrangler/config-schema.json",
  name: worker,
  main: "../src/index.ts",
  assets: { ...base.assets, directory: "../public" },
  d1_databases: [
    {
      binding: "DB",
      database_name: dbName,
      database_id: db.uuid,
      migrations_dir: "../../../packages/db/migrations",
    },
  ],
  r2_buckets: [{ binding: "BLOBS", bucket_name: bucket }],
  ...(ai ? { ai: { binding: "AI" } } : {}),
  routes: [{ pattern: domain, custom_domain: true }],
  workers_dev: false,
};
writeFileSync(
  configPath,
  `// Generated by scripts/deploy.ts for instance "${instance}". Not committed.\n${JSON.stringify(config, null, 2)}\n`,
);

// --- build + migrate + deploy ---------------------------------------------------------
step("assembling static assets");
const assets = spawnSync("node", ["scripts/assemble-assets.ts"], { cwd: APP, stdio: "inherit" });
if (assets.status !== 0) throw new Error("run `npm run build` at the repository root first");

step("applying D1 migrations (remote)");
console.log(wrangler(["d1", "migrations", "apply", "DB", "--remote", "-c", configPath], "y\n"));

step(`deploying ${worker} to https://${domain}`);
console.log(wrangler(["deploy", "-c", configPath]));

// --- secrets ------------------------------------------------------------------------------
let setupToken: string | undefined;
if (!previous.setupTokenSet || args["new-setup-token"]) {
  step("setting one-time SETUP_TOKEN secret");
  setupToken = randomBytes(24).toString("base64url");
  wrangler(["secret", "put", "SETUP_TOKEN", "-c", configPath], setupToken);
}
if (args["turn-key-id"] && args["turn-key-token"]) {
  step("setting TURN secrets");
  wrangler(["secret", "put", "TURN_KEY_ID", "-c", configPath], args["turn-key-id"]);
  wrangler(["secret", "put", "TURN_KEY_API_TOKEN", "-c", configPath], args["turn-key-token"]);
}

const state: InstanceState = {
  instance,
  domain,
  worker,
  database: { name: dbName, id: db.uuid },
  bucket,
  ai,
  setupTokenSet: previous.setupTokenSet || setupToken !== undefined,
};
writeFileSync(statePath, `${JSON.stringify(state, null, 2)}\n`);

console.log(`\n✔ Open Lounge Phone "${instance}" is live at https://${domain}`);
if (setupToken) {
  console.log(`\n  Create your household (works once, until the first household exists):`);
  console.log(`\n    https://${domain}/#setup=${setupToken}\n`);
}
if (!args["turn-key-id"]) {
  console.log(
    "  Calls between different networks need TURN: create a key in the Cloudflare dashboard\n" +
      "  (Realtime → TURN) and re-run with --turn-key-id <id> --turn-key-token <token>.",
  );
}
