#!/usr/bin/env python3
"""Generate firmware sources from the hardware and protocol sources of truth.

  main/board.h               from hardware/build/main/gpio_map.json (run `make -C hardware build`)
  main/fingerprint_words.c   from packages/core/src/fingerprint.ts (the list, verbatim)

Run from anywhere: `python3 firmware/tools/gen_board.py`. `--check` exits 1 when the committed
files differ from what the sources would generate (the fingerprint list is always checkable; the
pin map only when hardware/build exists).
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GPIO_MAP = ROOT / "hardware/build/main/gpio_map.json"
FINGERPRINT_TS = ROOT / "packages/core/src/fingerprint.ts"
MAIN = ROOT / "firmware/main"

# Keys in protocol order: digits 1-9 -> button index 0-8, digit 0 -> 9, then MENU and BACK.
KEY_ORDER = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "MENU", "BACK"]


def board_h(m: dict) -> str:
    n2g = m["net_to_gpio"]
    p = m["peripherals"]
    out = [
        "// Generated by firmware/tools/gen_board.py from hardware/build/main/gpio_map.json.",
        "// Do not edit by hand: change hardware/schematic/pin_table.yaml and regenerate.",
        f"// Board: {m['board']}, rev {m['rev']}; module: {m['module']}",
        "#pragma once",
        "",
        "#include \"sdkconfig.h\"",
        "",
    ]

    def define(name: str, value, note: str = "") -> None:
        out.append(f"#define {name:<24} {value}" + (f"  // {note}" if note else ""))

    out.append("// Keys: active low with internal pull-ups, in protocol order (index = button index;")
    out.append("// 10 = MENU, 11 = BACK).")
    for k in KEY_ORDER:
        info = m["keys"][k]
        note = info.get("note", "") or ""
        if info["gpio"] in (43, 44):
            note = "UART0 pin: the simulator build moves it (CONFIG_OLP_SIM)"
        define(f"PIN_KEY_{k}_HW", info["gpio"], note)
    out.append("")
    define("PIN_HOOK", n2g["HOOK"], "low = handset on the hook (internal pull-up)")
    define("PIN_JACK_DET", n2g["JACK_DET"], "high = plug in (internal pull-up)")
    define("PIN_BUZZER", n2g["BUZZER"], "piezo via NPN, ~4 kHz")
    define("PIN_STATUS_LED", n2g["STATUS_LED"], "active high")
    define("PIN_BOOT", n2g["BOOT"])
    out.append("")
    d = p["display"]
    define("PIN_EPD_CLK", d["spi"]["clk"])
    define("PIN_EPD_DIN", d["spi"]["mosi"])
    define("PIN_EPD_CS", d["spi"]["cs"])
    define("PIN_EPD_DC", d["dc"])
    define("PIN_EPD_RST", d["rst"])
    define("PIN_EPD_BUSY", d["busy"])
    out.append("")
    c = p["codec"]
    define("PIN_I2C_SDA", c["i2c"]["sda"])
    define("PIN_I2C_SCL", c["i2c"]["scl"])
    define("CODEC_I2C_ADDR", c["i2c"]["address_7bit"], c["part"])
    define("PIN_I2S_MCLK", c["i2s"]["mclk"])
    define("PIN_I2S_BCLK", c["i2s"]["bclk"])
    define("PIN_I2S_WS", c["i2s"]["ws"])
    define("PIN_I2S_DOUT", c["i2s"]["data_to_codec"], "to the codec (playback)")
    define("PIN_I2S_DIN", c["i2s"]["data_from_codec"], "from the codec (record)")
    out += [
        "",
        "// The Wokwi ESP32-S3 prints its console on UART0 (IO43/IO44), where the board has keys 6",
        "// and 7; the simulator build moves those two keys to free pins (no PSRAM in the sim).",
        "#if CONFIG_OLP_SIM",
        "#define PIN_KEY_6 35",
        "#define PIN_KEY_7 36",
        "#else",
        "#define PIN_KEY_6 PIN_KEY_6_HW",
        "#define PIN_KEY_7 PIN_KEY_7_HW",
        "#endif",
    ]
    for k in KEY_ORDER:
        if k not in ("6", "7"):
            out.append(f"#define PIN_KEY_{k} PIN_KEY_{k}_HW")
    out += [
        "",
        "#define KEY_COUNT 12",
        "#define KEY_MENU_INDEX 10",
        "#define KEY_BACK_INDEX 11",
        "#define KEY_PINS { " + ", ".join(f"PIN_KEY_{k}" for k in KEY_ORDER) + " }",
        "#define KEY_NAMES { " + ", ".join(f'"{k}"' for k in KEY_ORDER) + " }",
        "",
    ]
    return "\n".join(out)


def words_c() -> str:
    src = FINGERPRINT_TS.read_text()
    body = src.split("FINGERPRINT_WORDS: readonly string[] = [", 1)[1].split("];", 1)[0]
    words = re.findall(r'"([a-z]+)"', body)
    if len(words) != 256:
        sys.exit(f"expected 256 fingerprint words, found {len(words)}")
    lines = [
        "// Generated by firmware/tools/gen_board.py from packages/core/src/fingerprint.ts.",
        "// Fixed list: never reorder or edit (the app shows the same words for the same key).",
        '#include "identity.h"',
        "",
        "const char *const FINGERPRINT_WORDS[256] = {",
    ]
    for i in range(0, 256, 8):
        lines.append("    " + " ".join(f'"{w}",' for w in words[i : i + 8]))
    lines += ["};", ""]
    return "\n".join(lines)


def main() -> None:
    check = "--check" in sys.argv
    targets = {MAIN / "fingerprint_words.c": words_c()}
    if GPIO_MAP.exists():
        targets[MAIN / "board.h"] = board_h(json.loads(GPIO_MAP.read_text()))
    elif not check:
        sys.exit(f"{GPIO_MAP} is missing: run `make -C hardware build` first")
    stale = []
    for path, text in targets.items():
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(path)
        else:
            path.write_text(text)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        sys.exit("stale generated files: " + ", ".join(str(p.relative_to(ROOT)) for p in stale))


if __name__ == "__main__":
    main()
