// `openloungephone selfhost init`: writes compose.yaml and .env for Docker Compose.
import { randomBytes } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { relative, resolve } from "node:path";
import type { SelfhostOptions } from "./args.ts";
import type { Io } from "./io.ts";

/** The repository, for building the image when the files live outside a checkout. */
export const REPO_GIT = "https://github.com/Open-Lounge-Phone/open-lounge-phone.git#main";

export interface SelfhostChoices {
  publicUrl: string;
  coturn: boolean;
  livekit: boolean;
  openSignup: boolean;
  /** Build context for the server image: a path to this checkout, or the git URL. */
  context: string;
}

export interface SelfhostFiles {
  compose: string;
  env: string;
}

const hex = (bytes: number, random: (n: number) => Buffer) => random(bytes).toString("hex");

/** The two files, from the choices (pure apart from `random`). */
export function selfhostFiles(
  c: SelfhostChoices,
  random: (n: number) => Buffer = randomBytes,
): SelfhostFiles {
  const host = new URL(c.publicUrl).hostname;
  const profiles = [c.coturn ? "coturn" : "", c.livekit ? "livekit" : ""].filter(Boolean);
  const compose = [
    "# Open Lounge Phone, self-hosted. Generated by `openloungephone selfhost init`.",
    "# Start: docker compose up -d   Setup link: docker compose logs openloungephone",
    "# Optional services are compose profiles; .env's COMPOSE_PROFILES turns them on.",
    "services:",
    "  openloungephone:",
    "    build:",
    `      context: ${c.context}`,
    "      dockerfile: apps/server-selfhost/Dockerfile",
    "    restart: unless-stopped",
    "    env_file: .env",
    "    ports:",
    '      - "8787:8787"',
    "    volumes:",
    "      - openloungephone-data:/data",
    ...(c.livekit
      ? [
          "    # Lets the server reach LiveKit (host networking) at host.docker.internal.",
          "    extra_hosts:",
          '      - "host.docker.internal:host-gateway"',
        ]
      : []),
    ...(c.coturn
      ? [
          "",
          "  # TURN relay so calls connect across NATs and mobile networks (host networking: TURN",
          "  # needs a UDP port range). Open 3478/udp+tcp and 49160-49200/udp on your firewall.",
          "  coturn:",
          "    image: coturn/coturn:4.6",
          "    profiles: [coturn]",
          "    restart: unless-stopped",
          "    network_mode: host",
          "    command:",
          "      - --use-auth-secret",
          "      - --static-auth-secret=${TURN_SECRET:?set TURN_SECRET in .env}",
          "      - --realm=openloungephone",
          "      - --listening-port=3478",
          "      - --min-port=49160",
          "      - --max-port=49200",
          "      - --no-cli",
          "      - --no-tls",
          "      - --no-dtls",
          "      - --fingerprint",
        ]
      : []),
    ...(c.livekit
      ? [
          "",
          "  # Media relay for rooms of more than 4 people (host networking for its UDP ports).",
          "  livekit:",
          "    image: livekit/livekit-server:v1.9",
          "    profiles: [livekit]",
          "    restart: unless-stopped",
          "    network_mode: host",
          "    command:",
          "      - --bind=0.0.0.0",
          "      - --keys=${LIVEKIT_API_KEY:-openloungephone}: ${LIVEKIT_API_SECRET:?set LIVEKIT_API_SECRET in .env}",
        ]
      : []),
    "",
    "volumes:",
    "  openloungephone-data:",
    "",
  ].join("\n");

  const local = host === "localhost" || host.endsWith(".localhost");
  const env = [
    "# Open Lounge Phone settings. Generated by `openloungephone selfhost init`; keep this file",
    "# private (it holds secrets). All settings: docs/self-hosting.md.",
    "",
    "# Where people reach this server. Browsers only allow the microphone on https:// (or",
    "# http://localhost), and other servers find you by this name.",
    `PUBLIC_URL=${c.publicUrl}`,
    "",
    ...(profiles.length ? [`COMPOSE_PROFILES=${profiles.join(",")}`, ""] : []),
    "STUN_URLS=stun:stun.cloudflare.com:3478",
    ...(c.coturn
      ? [
          `TURN_URLS=turn:${host}:3478?transport=udp,turn:${host}:3478?transport=tcp`,
          `TURN_SECRET=${hex(32, random)}`,
        ]
      : [
          "# No TURN relay: calls between different networks may not connect.",
          "# TURN_URLS=",
          "# TURN_SECRET=",
        ]),
    "",
    c.openSignup
      ? "# Anyone may create an account (a public server).\nOPEN_SIGNUP=1"
      : "# Invite-only: people join by invite. OPEN_SIGNUP=1 lets anyone sign up.\n# OPEN_SIGNUP=1",
    ...(local
      ? ["", "# A localhost server can't federate with public servers; set an https:// PUBLIC_URL."]
      : []),
    ...(c.livekit
      ? [
          "",
          "# LiveKit (rooms of more than 4). LIVEKIT_URL is what browsers connect to: put it behind",
          "# your HTTPS proxy as wss:// (WebSockets included).",
          `LIVEKIT_URL=${local ? "ws://localhost:7880" : `wss://livekit.${host}`}`,
          "LIVEKIT_API_URL=http://host.docker.internal:7880",
          "LIVEKIT_API_KEY=openloungephone",
          `LIVEKIT_API_SECRET=${hex(32, random)}`,
        ]
      : []),
    "",
  ].join("\n");
  return { compose, env };
}

/** The steps to print after writing the files. */
export function nextSteps(c: SelfhostChoices, dir: string): string[] {
  const cd = dir === "." ? [] : [`  cd ${dir}`];
  const https = c.publicUrl.startsWith("https://");
  return [
    "Next steps:",
    ...cd,
    "  docker compose up -d",
    "  docker compose logs openloungephone     # prints your one-time setup link",
    ...(https
      ? [
          `  Put HTTPS in front of port 8787 for ${new URL(c.publicUrl).host} (e.g. Caddy:`,
          "  reverse_proxy localhost:8787), WebSockets included.",
        ]
      : [
          "  Open http://localhost:8787 on this machine; for phones elsewhere, use an https:// URL.",
        ]),
    ...(c.coturn
      ? ["  Open 3478/udp+tcp and 49160-49200/udp to this machine for the TURN relay."]
      : []),
    ...(c.livekit ? ["  Proxy LIVEKIT_URL (wss://…) to port 7880 for rooms of more than 4."] : []),
    "  Back up the openloungephone-data volume (database, voicemail, federation key).",
    "  Check it: npx openloungephone status " + c.publicUrl,
  ];
}

/** Where the image is built from: this checkout if `dir` is inside it, else the git URL. */
export function buildContext(dir: string, repoRoot: string): string {
  const rel = relative(resolve(dir), resolve(repoRoot));
  if (rel === "") return ".";
  if (rel.split(/[\\/]/).every((p) => p === "..")) return rel.replaceAll("\\", "/");
  return REPO_GIT;
}

export async function selfhostInit(
  opts: SelfhostOptions,
  io: Io,
  repoRoot: string,
  random: (n: number) => Buffer = randomBytes,
): Promise<number> {
  const ask = io.interactive && !opts.yes;
  const dir = resolve(opts.dir);
  const composePath = resolve(dir, "compose.yaml");
  const envPath = resolve(dir, ".env");
  const existing = [composePath, envPath].filter((p) => existsSync(p));
  if (existing.length && !opts.force) {
    io.err(`Not overwriting ${existing.join(" and ")} (use --force to replace them).`);
    return 1;
  }
  let publicUrl = opts.publicUrl;
  if (!publicUrl && ask) {
    const answer = await io.ask("Public URL people will use", "http://localhost:8787");
    publicUrl = answer.includes("://") ? answer : `https://${answer}`;
  }
  publicUrl = new URL(publicUrl ?? "http://localhost:8787").origin;
  const coturn =
    opts.coturn ??
    (ask
      ? await io.confirm("Bundle a TURN relay (coturn) for calls across networks?", true)
      : false);
  const livekit =
    opts.livekit ??
    (ask ? await io.confirm("Bundle LiveKit for rooms of more than 4 people?", false) : false);
  const openSignup =
    opts.openSignup ??
    (ask ? await io.confirm("Let anyone create an account (a public server)?", false) : false);
  const choices: SelfhostChoices = {
    publicUrl,
    coturn,
    livekit,
    openSignup,
    context: buildContext(dir, repoRoot),
  };
  const files = selfhostFiles(choices, random);
  mkdirSync(dir, { recursive: true });
  writeFileSync(composePath, files.compose);
  writeFileSync(envPath, files.env, { mode: 0o600 });
  chmodSync(envPath, 0o600);
  io.out(`Wrote ${composePath}`);
  io.out(`Wrote ${envPath} (mode 600; it holds secrets)`);
  io.out();
  for (const line of nextSteps(choices, opts.dir)) io.out(line);
  return 0;
}
